# Generated by Django 2.2.7 on 2020-01-01 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191229_2258'),
        ('blog', '0005_auto_20191124_0921'),
    ]

    operations = [
    ]
